### ISSUE TITLE
Persistence ViewModel for Multiple Widgets

### ISSUE THREAD

**Issue by Tusar0003** [NourEldinShobier/pmvvm#6]
Hello there,
I have been using PMVVM for multiple production level applications and I am really liking it's simplicity. But recently I am facing a problem.

Suppose I have several widgets which need to use same ViewModel. Such as: let's say there is a parent widget and few child widgets. All of the widgets need to use the same ViewModel. Right now what is  happening, every time the ViewModel is created newly when I navigate to a new widget. But how I can I have persistent ViewModel which will be created only once and will be shared to all parent and child widgets?

**Comment by NourEldinShobier** [comment]
Hi @Tusar0003 

If i understand you correctly, then:
- regarding sharing the VM with parents and children: you can only access/share the VM with the children, that's how the Provider package works
- regarding "every time the ViewModel is created newly when I navigate to a new widget": can you please provide a code sample that does so, cuz I tried to reproduce this error and failed

**Comment by Tusar0003** [comment]
Hello @NourEldinShobier 

- Regarding the first point, it is exactly what I want to do. How can I access the VM from child widget?
- Here I am providing a code sample for showing how I am initializing VM in my widget:

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MVVM(
      view: (_, __) => HomePageView(),
      viewModel: HomeViewModel(),
    );
  }
}

// ignore: must_be_immutable
class HomePageView extends StatelessView<HomeViewModel> {

  late BuildContext context;
  late HomeViewModel viewModel;

  @override
  Widget render(BuildContext context, HomeViewModel viewModel) {
    this.context = context;
    this.viewModel = viewModel;

    return Scaffold(
      appBar: appBar(),
      body: body(),
    );
  }
}

**Comment by NourEldinShobier** [comment]
- for the first point, there are multiple ways to consume the same VM:
  - the first approach is similar to the one we use to declare the primary view of the `MVVM`, by using `StatelessView` again for the children
  - the second one is using the `Consumer` or `Selector` widgets of the provider package and specifying which VM you would like to consume (cuz view models are just `ChangeNotifiers`)
  - this last one, you might need it if you are trying to consume the VM from within a `StatefulWidget`, is by using `context.fetch<VM>(listen: false/true)`
- as for the second point, I think you mean that the `init` method of the VM gets called multiple times, this happens when you are using the context of the view model to consume/listen to another variable (e.g: `context.fetch<VM>(listen: false/true)`). To stop this behavior, simply set `initOnce` of the `MVVM` widget to `true` and that will fix it

**Comment by Tusar0003** [comment]
thanks for the help...........

I think my problem has been resolved with this line of code

`context.fetch<VM>(listen: false/true)`
